/* SPDX-License-Identifier: Apache-2.0 */
package com.librestatic.opencinecam

import android.content.Intent
import android.net.Uri
import androidx.core.content.IntentCompat
import androidx.compose.material3.MaterialTheme
import androidx.compose.runtime.mutableStateOf
import androidx.compose.ui.semantics.SemanticsActions
import androidx.compose.ui.test.*
import androidx.compose.ui.test.junit4.v2.createComposeRule
import androidx.compose.ui.text.TextLayoutResult
import androidx.compose.ui.unit.dp
import androidx.test.platform.app.InstrumentationRegistry
import com.librestatic.opencinecam.storage.*
import java.io.File
import java.io.IOException
import java.util.UUID
import java.util.concurrent.CopyOnWriteArrayList
import java.util.concurrent.CountDownLatch
import java.util.concurrent.TimeUnit
import java.util.concurrent.atomic.AtomicBoolean
import java.util.concurrent.atomic.AtomicInteger
import org.junit.Assert.*
import org.junit.Rule
import org.junit.Test

/** Injected IO tests ownership and UI; the production intent builder is real. Separate UID tests
 * verify actual grants and generated bytes. These synthetic URIs are never read or deleted. */
class MediaSharingUiTest {
    @get:Rule val compose = createComposeRule()
    private val settings = mutableStateOf(MediaSharingSettings())
    private val selected = mutableStateOf(take())
    private val shown = mutableStateOf(true)
    private val calls = AtomicInteger()
    private val requests = CopyOnWriteArrayList<MediaSharingSettings>()
    private val results = CopyOnWriteArrayList<Prepared>()
    private val launches = CopyOnWriteArrayList<Intent>()
    private val failPrepare = AtomicBoolean()
    private val failLaunch = AtomicBoolean()
    private var hold: Hold? = null
    private val source = MediaShareSource { _, options ->
        calls.incrementAndGet(); requests += options
        hold?.waitForRelease()
        if (failPrepare.get()) throw IOException("Fixture export failure")
        Prepared().also { results += it }
    }

    @Test fun editingAllSelectionsDoesNotPrepareAndDisabledChoicesRetainPreferences() {
        show()
        for (content in MediaShareContent.entries) {
            reveal("content-$content").performClick(); reveal("content-$content").assertIsSelected()
            if (content == MediaShareContent.ORIGINALS_ONLY) {
                reveal("metadata-row").assertIsNotEnabled()
                reveal("lut").assertIsNotEnabled().assertIsOn()
            } else {
                for (metadata in MediaShareMetadata.entries) {
                    reveal("metadata-$metadata").performClick(); reveal("metadata-$metadata").assertIsSelected()
                    if (metadata == MediaShareMetadata.PRODUCTION) reveal("lut").assertIsNotEnabled()
                    else reveal("lut").assertIsEnabled()
                }
            }
        }
        reveal("lut").performClick().assertIsOff()
        compose.runOnIdle {
            assertEquals(MediaSharingSettings(MediaShareContent.METADATA_ONLY, MediaShareMetadata.BOTH, false), settings.value)
            assertEquals(0, calls.get()); assertTrue(launches.isEmpty())
        }
        node("cancel").performClick()
        node("dialog").assertDoesNotExist()
    }

    @Test fun incompleteOrMissingSlateNeverSilentlyFallsBackToOriginals() {
        show()
        for (status in LocalMediaRelationStatus.entries) {
            compose.runOnIdle { selected.value = take(status); settings.value = MediaSharingSettings() }
            if (status == LocalMediaRelationStatus.DECLARED) node("confirm").assertIsEnabled()
            else {
                node("confirm").assertIsNotEnabled()
                reveal("relation-required").assertExists()
            }
            reveal("content-ORIGINALS_ONLY").performClick()
            node("confirm").assertIsEnabled()
        }
        compose.runOnIdle { selected.value = take().copy(slate = null); settings.value = MediaSharingSettings() }
        node("confirm").assertIsNotEnabled()
        reveal("relation-required").assertExists()
        reveal("metadata-TECHNICAL").performClick()
        node("confirm").assertIsEnabled()
        reveal("metadata-PRODUCTION").performClick()
        node("confirm").assertIsNotEnabled()
        reveal("metadata-BOTH").performClick()
        node("confirm").assertIsNotEnabled()
        compose.runOnIdle { assertEquals(0, calls.get()); assertTrue(launches.isEmpty()) }
    }

    @Test fun confirmedChooserContainsEveryUriReadOnlyAndIsNotDeliveryEvidence() {
        show(); node("confirm").performClick()
        await { launches.size == 1 && results.singleOrNull()?.discardCalls?.get() == 1 }
        val result = results.single()
        val intent = launches.single()
        assertEquals(Intent.ACTION_SEND_MULTIPLE, intent.action)
        assertEquals(Intent.FLAG_GRANT_READ_URI_PERMISSION, intent.flags)
        val streams = IntentCompat.getParcelableArrayListExtra(intent, Intent.EXTRA_STREAM, Uri::class.java)!!.map { it.toString() }
        assertEquals(result.files.map { it.uri }, streams)
        assertEquals(result.files.size, intent.clipData!!.itemCount)
        assertEquals(streams, (0 until intent.clipData!!.itemCount).map { intent.clipData!!.getItemAt(it).uri.toString() })
        assertTrue(result.marked.get()); assertFalse(result.discardedBeforeHandoff.get())
        reveal("launched").assertTextEquals(text(R.string.media_share_launched))
        node("confirm").assertIsNotEnabled()
        compose.runOnIdle { assertEquals(1, calls.get()) }
    }

    @Test fun busyBlocksDoubleConfirmationAndCancelDiscardsLateResultWithoutChooser() {
        val barrier = Hold(); hold = barrier
        try {
            show(); node("confirm").performClick(); await { barrier.entered.count == 0L }
            node("confirm").assertIsNotEnabled()
            reveal("content-row").assertIsNotEnabled()
            node("cancel").performClick(); node("dialog").assertDoesNotExist()
            barrier.release.countDown()
            awaitDiscard()
            assertTrue(results.single().discardedBeforeHandoff.get())
            assertEquals(1, calls.get()); assertTrue(launches.isEmpty())
        } finally { barrier.release.countDown() }
    }

    @Test fun disposalRetiresPreparationAndCannotLaunchAfterReturningToGallery() {
        val barrier = Hold(); hold = barrier
        try {
            show(); node("confirm").performClick(); await { barrier.entered.count == 0L }
            compose.runOnIdle { shown.value = false }
            // Commit disposal before releasing IO: changing state alone has not removed the dialog.
            node("dialog").assertDoesNotExist()
            barrier.release.countDown(); awaitDiscard()
            assertTrue("Disposed preparation must be discarded before handoff", results.single().discardedBeforeHandoff.get())
            assertTrue("Disposed dialog must never launch the chooser", launches.isEmpty())
        } finally { barrier.release.countDown() }
    }

    @Test fun externallyChangedSelectionInvalidatesHeldRequestAndPreservesNewPreferences() {
        val barrier = Hold(); hold = barrier
        try {
            show(); node("confirm").performClick(); await { barrier.entered.count == 0L }
            compose.runOnIdle {
                selected.value = take().copy(id = "another-take")
                settings.value = MediaSharingSettings(MediaShareContent.ORIGINALS_ONLY, MediaShareMetadata.TECHNICAL, false)
            }
            node("confirm").assertIsEnabled()
            barrier.release.countDown(); awaitDiscard()
            assertTrue(launches.isEmpty()); assertTrue(results.single().discardedBeforeHandoff.get())
            compose.runOnIdle {
                assertEquals(MediaShareContent.ORIGINALS_ONLY, settings.value.content)
                assertEquals(listOf(MediaSharingSettings()), requests.toList())
            }
        } finally { barrier.release.countDown() }
    }

    @Test fun preparationFailureShowsRetryAndSelectionChangeWithoutFalseHandoff() {
        failPrepare.set(true)
        show(); node("confirm").performClick()
        await { compose.onAllNodesWithTag("media-share-error", useUnmergedTree = true).fetchSemanticsNodes().isNotEmpty() }
        reveal("error").assertTextEquals(text(R.string.media_share_error))
        node("confirm").assertIsEnabled(); node("launched").assertDoesNotExist()
        assertTrue(results.isEmpty()); assertTrue(launches.isEmpty())
        reveal("lut").performClick().assertIsOff()
        failPrepare.set(false)
        node("confirm").performClick(); await { launches.size == 1 }
        reveal("launched").assertExists()
        assertEquals(2, calls.get()); assertFalse(requests.last().includeReferencedLut)
    }

    @Test fun chooserFailureAfterMarkRetainsSessionAndNeverReportsSuccessfulLaunch() {
        failLaunch.set(true)
        show(); node("confirm").performClick(); awaitDiscard()
        reveal("error").assertExists(); node("launched").assertDoesNotExist()
        node("confirm").assertIsEnabled()
        assertTrue(results.single().marked.get())
        assertFalse(results.single().discardedBeforeHandoff.get())
        assertTrue(launches.isEmpty())
    }

    @Test fun doubleFontDialogControlsAndFullLabelsStayAccessible() {
        show(doubleFont = true)
        val choices = MediaShareContent.entries.map { "content-$it" } + MediaShareMetadata.entries.map { "metadata-$it" }
        for (tag in choices) reveal(tag).assertHeightIsAtLeast(48.dp)
        reveal("lut").assertHeightIsAtLeast(48.dp)
        node("confirm").assertHeightIsAtLeast(48.dp)
        node("cancel").assertHeightIsAtLeast(48.dp)
        reveal("help-toggle").performClick()
        reveal("lut-help-toggle").performClick()
        for (tag in choices.map { "$it-label" } + listOf("help", "lut-label", "lut-help", "temporary", "sources")) {
            assertUnclipped(reveal(tag), tag)
        }
        assertUnclipped(node("confirm-label"), "confirm-label")
        assertUnclipped(node("cancel-label"), "cancel-label")
        assertEquals(0, calls.get())
    }

    private fun show(doubleFont: Boolean = false) {
        compose.setContent {
            DeviceConfigurationOverride(DeviceConfigurationOverride.FontScale(if (doubleFont) 2f else 1f)) {
                MaterialTheme {
                    if (shown.value) MediaShareDialogContent(selected.value, settings.value,
                        { settings.value = it }, { shown.value = false }, source) { intent ->
                        check(results.last().marked.get()) { "Chooser ran before handoff ownership" }
                        if (failLaunch.get()) throw IllegalStateException("Fixture chooser unavailable")
                        launches += intent
                    }
                }
            }
        }
    }
    private fun node(tag: String) = compose.settingsNode("media-share-$tag", Regex("^(content|metadata)-[A-Z_]+(-label)?$").matches(tag))
    private fun reveal(tag: String) = node(tag).performScrollTo()
    private fun await(condition: () -> Boolean) = compose.waitUntil(timeoutMillis = 5000, condition = condition)
    private fun awaitDiscard() = await { results.singleOrNull()?.discardCalls?.get() == 1 }
    private fun text(id: Int) = InstrumentationRegistry.getInstrumentation().targetContext.getString(id)
    private fun assertUnclipped(node: SemanticsNodeInteraction, tag: String) {
        val layouts = mutableListOf<TextLayoutResult>()
        node.performSemanticsAction(SemanticsActions.GetTextLayoutResult) { assertTrue(it(layouts)) }
        assertEquals(1, layouts.size)
        assertFalse("Overflow: $tag ${layouts.single().size}", layouts.single().hasVisualOverflow)
    }
    private class Hold {
        val entered = CountDownLatch(1)
        val release = CountDownLatch(1)
        fun waitForRelease() {
            entered.countDown()
            // Deliberately noncooperative fixture: even a result returned after cancellation
            // must be owned and discarded, not lost at the dispatcher resumption boundary.
            val deadline = System.nanoTime() + TimeUnit.SECONDS.toNanos(10)
            while (release.count != 0L) {
                check(System.nanoTime() < deadline) { "Fixture release timed out" }
                try { release.await(100, TimeUnit.MILLISECONDS) } catch (_: InterruptedException) { }
            }
        }
    }
    private class Prepared : MediaSharePreparation {
        val marked = AtomicBoolean()
        val discardedBeforeHandoff = AtomicBoolean()
        val discardCalls = AtomicInteger()
        private val delegate = PreparedMediaShare(listOf(
            PreparedMediaShareFile("content://media/external_primary/images/media/1", "take.jpg", "image/jpeg", MediaShareRole.ORIGINAL),
            PreparedMediaShareFile("content://com.librestatic.opencinecam.mediaexports/media-exports/fixture/relationships.json", "relationships.json", "application/json", MediaShareRole.RELATIONSHIP)
        ), System.currentTimeMillis() + 86400000L,
            File(InstrumentationRegistry.getInstrumentation().targetContext.cacheDir, "media-share-ui-${UUID.randomUUID()}"))
        override val files get() = delegate.files
        override val expiresAtEpochMs get() = delegate.expiresAtEpochMs
        override fun buildIntent() = delegate.buildIntent()
        override fun markPublished() { delegate.markPublished(); marked.set(true) }
        override fun discard() {
            delegate.discard()
            if (!marked.get()) discardedBeforeHandoff.set(true)
            discardCalls.incrementAndGet()
        }
    }
    companion object {
        private fun take(status: LocalMediaRelationStatus = LocalMediaRelationStatus.DECLARED): LocalMediaTake {
            val image = LocalMediaArtifact("content://media/external_primary/images/media/1", "take.jpg", "image/jpeg", 100, 1700000000)
            val metadata = LocalMediaArtifact("content://media/external_primary/downloads/2", "take.json", "application/json", 200, 1700000000)
            return LocalMediaTake("fixture-take", image, listOf(image), listOf(metadata), LocalMediaKind.PHOTO,
                ProductionSlateSettings(project = "Fixture"), status)
        }
    }
}
