/* SPDX-License-Identifier: Apache-2.0 */
package com.librestatic.opencinecam.storage

import java.nio.ByteBuffer
import java.nio.ByteOrder
import org.junit.Assert.*
import org.junit.Test

class PreciseHdrColorTest {
    // Reference literals evaluated independently with 55-digit Decimal arithmetic from BT.2100,
    // not generated by invoking the Kotlin converter. Neutrals give E'=0.5 and E'=0.75 exactly.
    @Test fun pqAbsoluteNeutralReferences() {
        assertNeutral(502, PreciseHdrTransfer.PQ, 92.24570899406408)
        assertNeutral(721, PreciseHdrTransfer.PQ, 983.3778555870977)
        assertNeutral(940, PreciseHdrTransfer.PQ, 10000.0)
    }
    @Test fun hlgReferenceDisplayNeutralReferences() {
        assertNeutral(502, PreciseHdrTransfer.HLG, 50.69702849110048)
        assertNeutral(721, PreciseHdrTransfer.HLG, 203.15214593754532)
        assertNeutral(940, PreciseHdrTransfer.HLG, 1000.0)
    }
    @Test fun pqColoredNclReferenceUsesIndependentChannelEotfs() {
        val rgb = hdr10ToLinearBt2020(600, 400, 700, false, PreciseHdrTransfer.PQ)
        assertEquals(4760.061288967886, rgb.redNits, 1e-6)
        assertEquals(104.5586826554563, rgb.greenNits, 1e-7)
        assertEquals(25.04234872028912, rgb.blueNits, 1e-7)
    }
    @Test fun hlgColoredReferenceRequiresLuminanceCoupledOotf() {
        val rgb = hdr10ToLinearBt2020(600, 400, 700, false, PreciseHdrTransfer.HLG)
        assertEquals(487.7279055883091, rgb.redNits, 1e-6)
        assertEquals(65.54698370416149, rgb.greenNits, 1e-7)
        assertEquals(35.36421340816632, rgb.blueNits, 1e-7)
    }
    @Test fun blackAndNominalRangeEndpoints() {
        for (t in PreciseHdrTransfer.entries) {
            assertEquals(0xff000000.toInt(), hdr10ToSdrArgb(64, 512, 512, false, t))
            assertEquals(0xff000000.toInt(), hdr10ToSdrArgb(0, 512, 512, true, t))
            assertEquals(hdr10ToLinearBt2020(940, 512, 512, false, t), hdr10ToLinearBt2020(1023, 512, 512, true, t))
        }
    }
    @Test fun referenceSdrQuantizationIncludesReinhardAndSrgbRatherThanGammaOnly() {
        assertEquals(0xff989898.toInt(), hdr10ToSdrArgb(502, 512, 512, false, PreciseHdrTransfer.PQ))
        assertEquals(0xff7c7c7c.toInt(), hdr10ToSdrArgb(502, 512, 512, false, PreciseHdrTransfer.HLG))
        assertEquals(0xffbcbcbc.toInt(), hdr10ToSdrArgb(721, 512, 512, false, PreciseHdrTransfer.HLG))
        assertEquals(0xfffdfdfd.toInt(), hdr10ToSdrArgb(940, 512, 512, false, PreciseHdrTransfer.PQ))
        assertEquals(0xffebebeb.toInt(), hdr10ToSdrArgb(940, 512, 512, false, PreciseHdrTransfer.HLG))
    }
    @Test fun wideGamutReferenceClipsOnlyAfterLinear709AndToneMapping() {
        assertEquals(0xffff0000.toInt(), hdr10ToSdrArgb(600, 400, 700, false, PreciseHdrTransfer.PQ))
        assertEquals(0xffff3547.toInt(), hdr10ToSdrArgb(600, 400, 700, false, PreciseHdrTransfer.HLG))
    }
    @Test fun lowTwoBitsSurviveBeforeFinalEightBitQuantization() {
        // All four codes become 16 if prematurely right-shifted to 8 bits.
        val pq = listOf(0.0, 0.00005259120354165627, 0.00017082647925082613, 0.00034287426020625863)
        val hlg = listOf(0.0, 0.00002319768460764914, 0.00012243811340563057, 0.00032399301765118305)
        for (offset in 0..3) {
            assertEquals(pq[offset], hdr10ToLinearBt2020(64 + offset, 512, 512, false, PreciseHdrTransfer.PQ).redNits, 1e-12)
            assertEquals(hlg[offset], hdr10ToLinearBt2020(64 + offset, 512, 512, false, PreciseHdrTransfer.HLG).redNits, 1e-12)
        }
    }
    @Test fun neutralsAreMonotonicAndRemainNeutralAcrossTheEntireTenBitDomain() {
        for (t in PreciseHdrTransfer.entries) for (full in listOf(false, true)) {
            var previousLight = -1.0; var previousCode = -1
            for (y in 0..1023) {
                val rgb = hdr10ToLinearBt2020(y, 512, 512, full, t)
                assertTrue(rgb.redNits.isFinite() && rgb.redNits >= previousLight)
                assertEquals(rgb.redNits, rgb.greenNits, 1e-10)
                assertEquals(rgb.redNits, rgb.blueNits, 1e-10)
                val argb = hdr10ToSdrArgb(y, 512, 512, full, t)
                val code = argb and 255
                assertEquals(code, (argb ushr 8) and 255); assertEquals(code, (argb ushr 16) and 255)
                assertEquals(255, argb ushr 24); assertTrue(code >= previousCode)
                previousLight = rgb.redNits; previousCode = code
            }
        }
    }
    @Test fun legalSignalExcursionsAreClippedBeforeTransferWithoutNan() {
        for (t in PreciseHdrTransfer.entries) {
            assertEquals(0xff000000.toInt(), hdr10ToSdrArgb(0, 512, 512, false, t))
            for (y in listOf(0, 1023)) for (u in listOf(0, 1023)) for (v in listOf(0, 1023)) {
                val rgb = hdr10ToLinearBt2020(y, u, v, false, t)
                assertTrue(rgb.redNits.isFinite() && rgb.greenNits.isFinite() && rgb.blueNits.isFinite())
                assertEquals(255, hdr10ToSdrArgb(y, u, v, false, t) ushr 24)
            }
        }
    }
    @Test fun outOfDomainCodesAndFalseDepthClaimsAreRejected() {
        for (bad in listOf(-1, 1024, Int.MIN_VALUE, Int.MAX_VALUE)) {
            assertThrows(IllegalArgumentException::class.java) { hdr10ToSdrArgb(bad, 512, 512, false, PreciseHdrTransfer.PQ) }
            assertThrows(IllegalArgumentException::class.java) { hdr10ToSdrArgb(64, bad, 512, false, PreciseHdrTransfer.HLG) }
            assertThrows(IllegalArgumentException::class.java) { hdr10ToSdrArgb(64, 512, bad, false, PreciseHdrTransfer.PQ) }
        }
        assertEquals(10, PreciseHdrPreview(PreciseHdrTransfer.PQ).decodedBitDepth)
        for (depth in listOf(0, 8, 12, 16)) assertThrows(IllegalArgumentException::class.java) { PreciseHdrPreview(PreciseHdrTransfer.HLG, depth) }
    }
    @Test fun p010UsesLittleEndianIndependentlyOfByteBufferOrder() {
        val bytes = byteArrayOf(0x40, 0x55, 0x80.toByte(), 0xaa.toByte(), 0xc0.toByte(), 0xff.toByte())
        for (order in listOf(ByteOrder.BIG_ENDIAN, ByteOrder.LITTLE_ENDIAN)) {
            val buffer = ByteBuffer.wrap(bytes).order(order)
            assertEquals(341, readP010Sample(buffer, 6, 2, 0, 0))
            assertEquals(682, readP010Sample(buffer, 6, 2, 1, 0))
            assertEquals(1023, readP010Sample(buffer, 6, 2, 2, 0))
            assertEquals(order, buffer.order())
        }
    }
    @Test fun p010HonorsPositionStrideCropCoordinatesAndTruncatedLastRow() {
        val buffer = ByteBuffer.allocateDirect(32)
        buffer.put(19, 0x40); buffer.put(20, 0x55)
        buffer.position(3); buffer.limit(21); buffer.mark()
        assertEquals(341, readP010Sample(buffer.asReadOnlyBuffer(), 12, 4, 1, 1))
        assertEquals(341, readP010Sample(buffer, 12, 4, 1, 1))
        assertEquals(3, buffer.position()); assertEquals(21, buffer.limit())
        buffer.reset(); assertEquals(3, buffer.position())
    }
    @Test fun p010SliceAndSeparateChromaViewsUseTheirOwnOrigins() {
        val parent = ByteBuffer.wrap(byteArrayOf(9, 9, 0x40, 0x55, 0x80.toByte(), 0xaa.toByte(), 9, 9))
        parent.position(2); parent.limit(6)
        val cb = parent.slice(); parent.position(4)
        val cr = parent.slice()
        assertEquals(341, readP010Sample(cb, 4, 4, 0, 0))
        assertEquals(682, readP010Sample(cr, 4, 4, 0, 0))
        assertEquals(4, parent.position())
    }
    @Test fun p010RejectsMissingSecondByteCoordinatesAndRowCrossing() {
        val buffer = ByteBuffer.allocate(8)
        for ((row, pixel, x, y) in listOf(
            listOf(0, 2, 0, 0), listOf(2, 1, 0, 0), listOf(4, 2, -1, 0), listOf(4, 2, 0, -1),
            listOf(4, 2, 2, 0), listOf(4, 2, 0, 2), listOf(Int.MAX_VALUE, 2, 0, Int.MAX_VALUE),
            listOf(Int.MAX_VALUE, Int.MAX_VALUE, Int.MAX_VALUE, Int.MAX_VALUE))) {
            assertThrows(IllegalArgumentException::class.java) { readP010Sample(buffer, row, pixel, x, y) }
        }
        buffer.position(7)
        assertThrows(IllegalArgumentException::class.java) { readP010Sample(buffer, 2, 2, 0, 0) }
        buffer.limit(7)
        assertThrows(IllegalArgumentException::class.java) { readP010Sample(buffer, 2, 2, 0, 0) }
    }
    @Test fun p010RejectsEveryNonzeroUnusedLowBit() {
        for (bit in 0..5) {
            val buffer = ByteBuffer.wrap(byteArrayOf((1 shl bit).toByte(), 0x80.toByte()))
            assertThrows(IllegalArgumentException::class.java) { readP010Sample(buffer, 2, 2, 0, 0) }
        }
    }
    private fun assertNeutral(y: Int, t: PreciseHdrTransfer, nits: Double) {
        val rgb = hdr10ToLinearBt2020(y, 512, 512, false, t)
        assertEquals(nits, rgb.redNits, 1e-6)
        assertEquals(nits, rgb.greenNits, 1e-6)
        assertEquals(nits, rgb.blueNits, 1e-6)
    }
}
